runtime: go
api_version: go1.8

includes:
- secret.yaml

handlers:
- url: /favicon.(.*)
  static_files: static/images/favicon.\1
  upload: static/images/favicon.(.*)

- url: /css/(.*\.css)
  mime_type: text/css
  static_files: static/css/\1
  upload: static/css/(.*\.css)

- url: /images/(.*)
  static_files: static/images/\1
  upload: static/images/(.*)
- url: /.*
  script: src/_go_app
